/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-RTI
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RTI_API_H
#define INCLUDED_RTI_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_RTI_EXPORTS
#define RTI_API __GR_ATTR_EXPORT
#else
#define RTI_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RTI_API_H */
